class Units {
  String name;
  int id;
  int propertyId;
  String position;
  int statusId;
  String status;
  int size;
  int price;
  int bedrooms;

  Units(
      {required this.bedrooms,
      required this.price,
      required this.propertyId,
      required this.id,
      required this.status,
      required this.name,
      required this.position,
      required this.statusId,
      required this.size});
}

// var units = {
//   '1': [
//     Units(propertyId: '1',
//         id: '1',
//         size: '156',
//         price: 1561641,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '2',
//         size: '140',
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G07',
//         position: 'R100',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '3',
//         size: '140',
//         price: 156100,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '4',
//         size: '140',
//         price: 1000000,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '5',
//         size: '140',
//         price: 1586700,
//         bedrooms: 3,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '6',
//         size: '140',
//         price: 1250000,
//         bedrooms: 3,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
//   ],
//   '2': [
//     Units(propertyId: '1',
//         id: '1',
//         size: '120',
//         price: 15652641,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '2',
//         size: '120',
//
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G07',
//         position: 'R100',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '3',
//         size: '120',
//
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '4',
//         size: '120',
//         price: 215500,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '5',
//         size: '120',
//         price: 1561541,
//         bedrooms: 4,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '6',
//         size: '120',
//
//         price: 15610000,
//         bedrooms: 4,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
//   ],
//   '3': [
//     Units(propertyId: '1',
//         id: '1',
//         size: '120',
//
//         price: 156100,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//   ],
//   '4': [
//     Units(propertyId: '1',
//         id: '3',
//         size: '120',
//
//         price: 1561500,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '4',
//         size: '120',
//
//         price: 156000,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '5',
//         size: '120',
//
//         price: 156100,
//         bedrooms: 3,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '6',
//         size: '120',
//
//         price: 1561500,
//         bedrooms: 2,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
//   ]
// };
// var unitsList = [
//     Units(propertyId: '1',
//         id: '1',
//         size: '156',
//         price: 1561641,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '2',
//         size: '140',
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G07',
//         position: 'R100',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '3',
//         size: '140',
//         price: 156100,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '1',
//         id: '4',
//         size: '140',
//         price: 1000000,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '2',
//         id: '5',
//         size: '140',
//         price: 1586700,
//         bedrooms: 3,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '2',
//         id: '6',
//         size: '140',
//         price: 1250000,
//         bedrooms: 3,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
//     Units(propertyId: '1',
//         id: '2',
//         size: '120',
//         price: 15652641,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//     Units(propertyId: '2',
//         id: '2',
//         size: '120',
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G07',
//         position: 'R100',
//         statusId: '1'),
//     Units(propertyId: '2',
//         id: '3',
//         size: '120',
//         price: 1561541,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '2',
//         id: '4',
//         size: '120',
//         price: 215500,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '2',
//         id: '5',
//         size: '120',
//         price: 1561541,
//         bedrooms: 4,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '2',
//         id: '6',
//         size: '120',
//
//         price: 15610000,
//         bedrooms: 4,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
//     Units(propertyId: '3',
//         id: '1',
//         size: '120',
//
//         price: 156100,
//         bedrooms: 2,
//         name: 'PF T2 G05',
//         position: 'R108',
//         statusId: '1'),
//     Units(propertyId: '3',
//         id: '3',
//         size: '120',
//
//         price: 1561500,
//         bedrooms: 2,
//         name: 'PF T2 G01',
//         position: 'R104',
//         statusId: '0'),
//     Units(propertyId: '3',
//         id: '4',
//         size: '120',
//
//         price: 156000,
//         bedrooms: 4,
//         name: 'PF T2 G05',
//         position: 'R107',
//         statusId: '0'),
//     Units(propertyId: '4',
//         id: '5',
//         size: '120',
//
//         price: 156100,
//         bedrooms: 3,
//         name: 'PF T2 G09',
//         position: 'R144',
//         statusId: '1'),
//     Units(propertyId: '4',
//         id: '6',
//         size: '120',
//
//         price: 1561500,
//         bedrooms: 2,
//         name: 'PF T2 G12',
//         position: 'R105',
//         statusId: '1'),
// ];
